spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  #    database-platform: org.hibernate.dialect.Oracle12cDialect
  #    open-in-view: false

  datasource:
    url: jdbc:mariadb://localhost:43306/qrService
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5